package com.view;

import com.controller.ControllerAdmin;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public final class AdminGUI extends javax.swing.JFrame {
    
    public AdminGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tableBuku.getTableHeader().setReorderingAllowed(false);
        tableKaryawan.getTableHeader().setReorderingAllowed(false);
        tableRiwayatPeminjaman.getTableHeader().setReorderingAllowed(false);
    }
    
    private void changePanel(JPanel panel, JPanel newPanel){
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        
        panel.add(newPanel);
        panel.repaint();
        panel.revalidate();
    } 
    
    
    
    private void clearFieldBuku(){
        txtKodeBuku.setText("");
        txtJudulBuku.setText("");
        txtPenulisBuku.setText("");
    }
    
    private void clearFieldKaryawan(){
        txtIdKaryawan.setText("");
        txtNamaKaryawan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        introPanelAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBuku = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKodeBuku = new javax.swing.JTextField();
        txtPenulisBuku = new javax.swing.JTextField();
        txtJudulBuku = new javax.swing.JTextField();
        btnInsertBuku = new javax.swing.JButton();
        btnUpdateBuku = new javax.swing.JButton();
        btnDeleteBuku = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        panelKaryawan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdKaryawan = new javax.swing.JTextField();
        txtNamaKaryawan = new javax.swing.JTextField();
        btnUpdateKaryawan = new javax.swing.JButton();
        btnDeleteKaryawan = new javax.swing.JButton();
        btnInsertKaryawan = new javax.swing.JButton();
        comboPenanggungjawab = new javax.swing.JComboBox<>();
        btnBatalKaryawan = new javax.swing.JButton();
        panelRiwayat = new javax.swing.JPanel();
        lblRiwayatPeminjaman = new javax.swing.JLabel();
        panelTabel = new javax.swing.JPanel();
        introPanelBawah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelTabelBuku = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        panelTabelKaryawan = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableKaryawan = new javax.swing.JTable();
        panelRiwayatPeminjaman = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRiwayatPeminjaman = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        btnBuku = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnRiwayatPeminjaman = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CRUD Admin");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelInput.setLayout(new java.awt.CardLayout());

        introPanelAtas.setBackground(new java.awt.Color(97, 130, 100));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("SELAMAT DATANG");

        javax.swing.GroupLayout introPanelAtasLayout = new javax.swing.GroupLayout(introPanelAtas);
        introPanelAtas.setLayout(introPanelAtasLayout);
        introPanelAtasLayout.setHorizontalGroup(
            introPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introPanelAtasLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(208, 208, 208))
        );
        introPanelAtasLayout.setVerticalGroup(
            introPanelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, introPanelAtasLayout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        panelInput.add(introPanelAtas, "card4");

        panelBuku.setBackground(new java.awt.Color(97, 130, 100));
        panelBuku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Buku");
        panelBuku.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul Buku");
        panelBuku.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status Buku");
        panelBuku.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        panelBuku.add(txtKodeBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, -1));
        panelBuku.add(txtPenulisBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 190, -1));
        panelBuku.add(txtJudulBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, -1));

        btnInsertBuku.setBackground(new java.awt.Color(176, 217, 177));
        btnInsertBuku.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnInsertBuku.setForeground(new java.awt.Color(0, 51, 51));
        btnInsertBuku.setText("Insert");
        btnInsertBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertBukuActionPerformed(evt);
            }
        });
        panelBuku.add(btnInsertBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 90, 40));

        btnUpdateBuku.setBackground(new java.awt.Color(176, 217, 177));
        btnUpdateBuku.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnUpdateBuku.setForeground(new java.awt.Color(0, 51, 51));
        btnUpdateBuku.setText("Update");
        btnUpdateBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBukuActionPerformed(evt);
            }
        });
        panelBuku.add(btnUpdateBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 90, 40));

        btnDeleteBuku.setBackground(new java.awt.Color(176, 217, 177));
        btnDeleteBuku.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnDeleteBuku.setForeground(new java.awt.Color(0, 51, 51));
        btnDeleteBuku.setText("Delete");
        btnDeleteBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBukuActionPerformed(evt);
            }
        });
        panelBuku.add(btnDeleteBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 90, 40));

        btnBatal.setBackground(new java.awt.Color(176, 217, 177));
        btnBatal.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(0, 51, 51));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelBuku.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 90, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Penulis Buku");
        panelBuku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Tidak Tersedia" }));
        comboStatus.setEnabled(false);
        panelBuku.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, -1));

        panelInput.add(panelBuku, "card2");

        panelKaryawan.setBackground(new java.awt.Color(97, 130, 100));
        panelKaryawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Karyawan");
        panelKaryawan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Karyawan");
        panelKaryawan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Penanggung Jawab");
        panelKaryawan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        panelKaryawan.add(txtIdKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, -1));
        panelKaryawan.add(txtNamaKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, -1));

        btnUpdateKaryawan.setBackground(new java.awt.Color(176, 217, 177));
        btnUpdateKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnUpdateKaryawan.setForeground(new java.awt.Color(0, 51, 51));
        btnUpdateKaryawan.setText("Update");
        btnUpdateKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKaryawanActionPerformed(evt);
            }
        });
        panelKaryawan.add(btnUpdateKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 90, 40));

        btnDeleteKaryawan.setBackground(new java.awt.Color(176, 217, 177));
        btnDeleteKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnDeleteKaryawan.setForeground(new java.awt.Color(0, 51, 51));
        btnDeleteKaryawan.setText("Delete");
        btnDeleteKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKaryawanActionPerformed(evt);
            }
        });
        panelKaryawan.add(btnDeleteKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 90, 40));

        btnInsertKaryawan.setBackground(new java.awt.Color(176, 217, 177));
        btnInsertKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnInsertKaryawan.setForeground(new java.awt.Color(0, 51, 51));
        btnInsertKaryawan.setText("Insert");
        btnInsertKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertKaryawanActionPerformed(evt);
            }
        });
        panelKaryawan.add(btnInsertKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, 40));

        panelKaryawan.add(comboPenanggungjawab, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 190, -1));

        btnBatalKaryawan.setBackground(new java.awt.Color(176, 217, 177));
        btnBatalKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnBatalKaryawan.setForeground(new java.awt.Color(0, 51, 51));
        btnBatalKaryawan.setText("Batal");
        btnBatalKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalKaryawanActionPerformed(evt);
            }
        });
        panelKaryawan.add(btnBatalKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 90, 40));

        panelInput.add(panelKaryawan, "card3");

        panelRiwayat.setBackground(new java.awt.Color(97, 130, 100));

        lblRiwayatPeminjaman.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lblRiwayatPeminjaman.setForeground(new java.awt.Color(0, 51, 51));
        lblRiwayatPeminjaman.setText("RIWAYAT PEMINJAMAN");

        javax.swing.GroupLayout panelRiwayatLayout = new javax.swing.GroupLayout(panelRiwayat);
        panelRiwayat.setLayout(panelRiwayatLayout);
        panelRiwayatLayout.setHorizontalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRiwayatLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblRiwayatPeminjaman)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelRiwayatLayout.setVerticalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
            .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRiwayatLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblRiwayatPeminjaman)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelInput.add(panelRiwayat, "card3");

        panelTabel.setLayout(new java.awt.CardLayout());

        introPanelBawah.setBackground(new java.awt.Color(97, 130, 100));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("DI PERPUSTAKAAN");

        javax.swing.GroupLayout introPanelBawahLayout = new javax.swing.GroupLayout(introPanelBawah);
        introPanelBawah.setLayout(introPanelBawahLayout);
        introPanelBawahLayout.setHorizontalGroup(
            introPanelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introPanelBawahLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel5)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        introPanelBawahLayout.setVerticalGroup(
            introPanelBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(introPanelBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        panelTabel.add(introPanelBawah, "card5");

        panelTabelBuku.setBackground(new java.awt.Color(208, 231, 210));

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul Buku", "Penulis Buku", "Status Buku"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBuku);

        javax.swing.GroupLayout panelTabelBukuLayout = new javax.swing.GroupLayout(panelTabelBuku);
        panelTabelBuku.setLayout(panelTabelBukuLayout);
        panelTabelBukuLayout.setHorizontalGroup(
            panelTabelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(panelTabelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
        );
        panelTabelBukuLayout.setVerticalGroup(
            panelTabelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
            .addGroup(panelTabelBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelBukuLayout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        panelTabel.add(panelTabelBuku, "card4");

        panelTabelKaryawan.setBackground(new java.awt.Color(208, 231, 210));

        tableKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "ID Penanggung Jawab"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKaryawanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableKaryawan);

        javax.swing.GroupLayout panelTabelKaryawanLayout = new javax.swing.GroupLayout(panelTabelKaryawan);
        panelTabelKaryawan.setLayout(panelTabelKaryawanLayout);
        panelTabelKaryawanLayout.setHorizontalGroup(
            panelTabelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(panelTabelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
        );
        panelTabelKaryawanLayout.setVerticalGroup(
            panelTabelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
            .addGroup(panelTabelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        panelTabel.add(panelTabelKaryawan, "card4");

        panelRiwayatPeminjaman.setBackground(new java.awt.Color(208, 231, 210));

        tableRiwayatPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Peminjaman", "User ID", "Kode Buku", "Tanggal Peminjaman", "ID Karyawan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRiwayatPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRiwayatPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableRiwayatPeminjaman);

        javax.swing.GroupLayout panelRiwayatPeminjamanLayout = new javax.swing.GroupLayout(panelRiwayatPeminjaman);
        panelRiwayatPeminjaman.setLayout(panelRiwayatPeminjamanLayout);
        panelRiwayatPeminjamanLayout.setHorizontalGroup(
            panelRiwayatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(panelRiwayatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
        );
        panelRiwayatPeminjamanLayout.setVerticalGroup(
            panelRiwayatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
            .addGroup(panelRiwayatPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        panelTabel.add(panelRiwayatPeminjaman, "card4");

        panelButton.setBackground(new java.awt.Color(208, 231, 210));

        btnBuku.setBackground(new java.awt.Color(121, 172, 120));
        btnBuku.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBuku.setForeground(new java.awt.Color(0, 51, 51));
        btnBuku.setText("Buku");
        btnBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBukuMouseClicked(evt);
            }
        });
        btnBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukuActionPerformed(evt);
            }
        });

        btnKaryawan.setBackground(new java.awt.Color(121, 172, 120));
        btnKaryawan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(0, 51, 51));
        btnKaryawan.setText("Karyawan");
        btnKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseClicked(evt);
            }
        });
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });

        btnRiwayatPeminjaman.setBackground(new java.awt.Color(121, 172, 120));
        btnRiwayatPeminjaman.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRiwayatPeminjaman.setForeground(new java.awt.Color(0, 51, 51));
        btnRiwayatPeminjaman.setText("Riwayat Peminjaman");
        btnRiwayatPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatPeminjamanActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(121, 172, 120));
        btnLogOut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(0, 51, 51));
        btnLogOut.setText("LOGOUT");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRiwayatPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuku)
                    .addComponent(btnKaryawan)
                    .addComponent(btnRiwayatPeminjaman)
                    .addComponent(btnLogOut))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 431, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(260, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(panelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertBukuActionPerformed
        if (txtKodeBuku.getText().matches("(.*)'(.*)") || txtJudulBuku.getText().matches("(.*)'(.*)") || txtPenulisBuku.getText().matches("(.*)'(.*)")) {
            JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
        }else{
            if (txtKodeBuku.getText().equals("") || txtJudulBuku.getText().equals("") || txtPenulisBuku.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "SEMUA DATA BUKU HARUS TERISI");
            }else {
                boolean success = ControllerAdmin.insertDataBuku(txtKodeBuku.getText(),txtJudulBuku.getText(),txtPenulisBuku.getText(), (String) comboStatus.getSelectedItem());
                if (success) {
                    JOptionPane.showMessageDialog(null, "BUKU BERHASIL DITAMBAHKAN");
                    btnBukuActionPerformed(evt);
                    clearFieldBuku();
                }
            }
        }
    }//GEN-LAST:event_btnInsertBukuActionPerformed

    private void btnDeleteBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBukuActionPerformed
        int chooseRow = tableBuku.getSelectedRow();
        if (chooseRow == -1) {
            JOptionPane.showMessageDialog(null, "HARAP PILIH DATA BUKU YANG INGIN DI HAPUS DI TABLE BAWAH");
        }else{
            try {
                int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin ?", "HAPUS BUKU", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    Object selectedRow = tableBuku.getValueAt(chooseRow, 0);
                    ControllerAdmin.deleteDataBuku(selectedRow);
                    btnBukuActionPerformed(evt);
                    JOptionPane.showMessageDialog(null, "BUKU BERHASIL DI HAPUS");
                    clearFieldBuku();
                    btnBukuActionPerformed(evt);
                    txtKodeBuku.setEnabled(true);
                }else clearFieldBuku(); txtKodeBuku.setEnabled(true); comboStatus.setEnabled(false); comboStatus.setSelectedIndex(0);
            } catch (SQLException ex) {
                Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteBukuActionPerformed

    private void btnUpdateBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBukuActionPerformed
        int chooseRow = tableBuku.getSelectedRow();
        if (chooseRow == -1) {
            JOptionPane.showMessageDialog(null, "HARAP PILIH DATA BUKU YANG INGIN DI UPDATE DI TABLE BAWAH");
        }else{
            try {
                if (txtKodeBuku.getText().matches("(.*)'(.*)") || txtJudulBuku.getText().matches("(.*)'(.*)") || txtPenulisBuku.getText().matches("(.*)'(.*)")) {
                    JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
                }else{
                    ControllerAdmin.updateDataBuku(txtKodeBuku.getText(),txtJudulBuku.getText(),txtPenulisBuku.getText(), (String) comboStatus.getSelectedItem());
                    btnBukuActionPerformed(evt);
                    JOptionPane.showMessageDialog(null, "DATA BUKU BERHASIL DIPERBARUI");
                    txtKodeBuku.setEnabled(true);
                    comboStatus.setEnabled(false);
                    comboStatus.setSelectedIndex(0);
                    clearFieldBuku(); 
                }
            } catch (SQLException ex) {
                Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateBukuActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        comboStatus.setEnabled(true);
        txtKodeBuku.setEnabled(false);
        int chooseRow = tableBuku.getSelectedRow();
        Object selectedRow = tableBuku.getValueAt(chooseRow, 0);
        String[] rowData = ControllerAdmin.setTextFieldBuku(selectedRow);
        txtKodeBuku.setText(rowData[0]);
        txtJudulBuku.setText(rowData[1]);
        txtPenulisBuku.setText(rowData[2]);
    }//GEN-LAST:event_tableBukuMouseClicked

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        changePanel(panelTabel, panelTabelKaryawan);
        changePanel(panelInput, panelKaryawan);
        clearFieldKaryawan();
        comboPenanggungjawab.removeAllItems();
        
        try {
            ArrayList<String> idPenanggungjawab = ControllerAdmin.setRadioId();
            for (String string : idPenanggungjawab) {
                comboPenanggungjawab.addItem(string);
            }
            DefaultTableModel tableModelKaryawan = (DefaultTableModel) tableKaryawan.getModel();
            tableModelKaryawan.setRowCount(0);
            ArrayList<Object> tableContent= ControllerAdmin.createTableContent("karyawan");
            ArrayList<String[]> barisKaryawan = ControllerAdmin.showTableContent(tableContent);
            for (String[] strings : barisKaryawan) {
                tableModelKaryawan.addRow(strings);

            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKaryawanMouseClicked

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        changePanel(panelTabel, panelTabelBuku);
        changePanel(panelInput, panelBuku);
        clearFieldBuku();
        txtKodeBuku.setEnabled(true);

        try {
            DefaultTableModel tableModelBuku = (DefaultTableModel) tableBuku.getModel();
            tableModelBuku.setRowCount(0);
            ArrayList<Object> tableContent= ControllerAdmin.createTableContent("buku");
            ArrayList<String[]> barisBuku = ControllerAdmin.showTableContent(tableContent);
            for (String[] strings : barisBuku) {
                tableModelBuku.addRow(strings);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBukuActionPerformed

    private void btnBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBukuMouseClicked

    }//GEN-LAST:event_btnBukuMouseClicked

    private void btnInsertKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertKaryawanActionPerformed
        try {
            if (txtIdKaryawan.getText().matches("(.*)'(.*)") || txtNamaKaryawan.getText().matches("(.*)'(.*)")) {
                JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
            }else{
                ArrayList<String> idPenanggungjawab = ControllerAdmin.setRadioId();            
                if (txtIdKaryawan.getText().equals("") || txtNamaKaryawan.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "SEMUA DATA KARYAWAN HARUS TERISI");
                }else {
                    if (idPenanggungjawab.isEmpty()) {
                        boolean success = ControllerAdmin.insertDataKaryawan(txtIdKaryawan.getText(),txtNamaKaryawan.getText(),txtIdKaryawan.getText());
                        if (success) {
                            JOptionPane.showMessageDialog(null, "KARYAWAN BERHASIL DITAMBAHKAN");
                            btnKaryawanActionPerformed(evt);
                            clearFieldBuku(); 
                        }
                    }else{
                        boolean success = ControllerAdmin.insertDataKaryawan(txtIdKaryawan.getText(),txtNamaKaryawan.getText(),comboPenanggungjawab.getSelectedItem());
                        if (success) {
                            JOptionPane.showMessageDialog(null, "KARYAWAN BERHASIL DITAMBAHKAN");
                            btnKaryawanActionPerformed(evt);
                            clearFieldBuku(); 
                        }
                    }
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInsertKaryawanActionPerformed

    private void btnDeleteKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKaryawanActionPerformed
        int chooseRow = tableKaryawan.getSelectedRow();
        if (chooseRow == -1) {
            JOptionPane.showMessageDialog(null, "HARAP PILIH DATA KARYAWAN YANG INGIN DI HAPUS DI TABLE BAWAH");
        }else{
            try {
                Object selectedRow = tableKaryawan.getValueAt(chooseRow, 0);
                ControllerAdmin.deleteDataKaryawan(selectedRow);
                btnKaryawanActionPerformed(evt);
                JOptionPane.showMessageDialog(null, "KARYAWAN BERHASIL DI HAPUS");
                clearFieldKaryawan();
                btnKaryawanActionPerformed(evt);
                txtIdKaryawan.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteKaryawanActionPerformed

    private void tableKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKaryawanMouseClicked
        txtIdKaryawan.setEnabled(false);
        int chooseRow = tableKaryawan.getSelectedRow();
        Object selectedRow = tableKaryawan.getValueAt(chooseRow, 0);
        String[] rowData = ControllerAdmin.setTextFieldKaryawan(selectedRow);
        txtIdKaryawan.setText(rowData[0]);
        txtNamaKaryawan.setText(rowData[1]);
        comboPenanggungjawab.setSelectedItem(rowData[2]);
    }//GEN-LAST:event_tableKaryawanMouseClicked

    private void btnUpdateKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKaryawanActionPerformed
        int chooseRow = tableKaryawan.getSelectedRow();
        if (chooseRow == -1) {
            JOptionPane.showMessageDialog(null, "HARAP PILIH DATA KARYAWAN YANG INGIN DI UPDATE DI TABLE BAWAH");
        }else{
            try {
                if (txtIdKaryawan.getText().matches("(.*)'(.*)") || txtNamaKaryawan.getText().matches("(.*)'(.*)")) {
                    JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
                }else{
                    ControllerAdmin.updateDataKaryawan(txtIdKaryawan.getText(),txtNamaKaryawan.getText(),comboPenanggungjawab.getSelectedItem());
                    btnKaryawanActionPerformed(evt);
                    JOptionPane.showMessageDialog(null, "DATA KARYAWAN BERHASIL DIPERBARUI");
                    txtIdKaryawan.setEnabled(true);
                    clearFieldKaryawan();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUpdateKaryawanActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "APAKAH ANDA YAKIN ?");
        if (answer == 1 || answer == 2 || answer == -1) {
            
        }else{
           this.dispose(); 
           new LoginGUI().setVisible(true);
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirm = JOptionPane.showConfirmDialog(null, "ANDA YAKIN INGIN KELUAR","Konformasi Keluar",JOptionPane.YES_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void tableRiwayatPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRiwayatPeminjamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableRiwayatPeminjamanMouseClicked

    private void btnRiwayatPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatPeminjamanActionPerformed
        changePanel(panelTabel, panelRiwayatPeminjaman);
        changePanel(panelInput, panelRiwayat);
        txtKodeBuku.setEnabled(true);

        try {
            DefaultTableModel tableModelRiwayat = (DefaultTableModel) tableRiwayatPeminjaman.getModel();
            tableModelRiwayat.setRowCount(0);
            ArrayList<Object> tableContent= ControllerAdmin.createTableContent("peminjaman");
            ArrayList<String[]> barisBuku = ControllerAdmin.showTableContent(tableContent);
            for (String[] strings : barisBuku) {
                tableModelRiwayat.addRow(strings);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRiwayatPeminjamanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clearFieldBuku();
        txtKodeBuku.setEnabled(true);
        comboStatus.setEnabled(false);
        comboStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBatalKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalKaryawanActionPerformed
        clearFieldBuku();
        txtIdKaryawan.setEnabled(true);
    }//GEN-LAST:event_btnBatalKaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalKaryawan;
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnDeleteBuku;
    private javax.swing.JButton btnDeleteKaryawan;
    private javax.swing.JButton btnInsertBuku;
    private javax.swing.JButton btnInsertKaryawan;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRiwayatPeminjaman;
    private javax.swing.JButton btnUpdateBuku;
    private javax.swing.JButton btnUpdateKaryawan;
    private javax.swing.JComboBox<String> comboPenanggungjawab;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JPanel introPanelAtas;
    private javax.swing.JPanel introPanelBawah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblRiwayatPeminjaman;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBuku;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelKaryawan;
    private javax.swing.JPanel panelRiwayat;
    private javax.swing.JPanel panelRiwayatPeminjaman;
    private javax.swing.JPanel panelTabel;
    private javax.swing.JPanel panelTabelBuku;
    private javax.swing.JPanel panelTabelKaryawan;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTable tableKaryawan;
    private javax.swing.JTable tableRiwayatPeminjaman;
    private javax.swing.JTextField txtIdKaryawan;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JTextField txtKodeBuku;
    private javax.swing.JTextField txtNamaKaryawan;
    private javax.swing.JTextField txtPenulisBuku;
    // End of variables declaration//GEN-END:variables
}
