/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.controller.ControllerAccount;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public final class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
    public LoginGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    private void changePanel(JPanel panel, JPanel newPanel){
        panel.removeAll();
        panel.repaint();
        panel.revalidate();
        
        panel.add(newPanel);
        panel.repaint();
        panel.revalidate();
    } 
    
    private void clearField(){
        txtUserIdNew.setText("");
        txtPasswordNew.setText("");
        txtName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtUserId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radioAdmin = new javax.swing.JRadioButton();
        radioMember = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPasswordNew = new javax.swing.JPasswordField();
        txtUserIdNew = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        mainPanel.setLayout(new java.awt.CardLayout());

        panelLogin.setBackground(new java.awt.Color(97, 130, 100));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBackground(new java.awt.Color(0, 51, 51));
        txtPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        panelLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 260, 40));

        txtUserId.setBackground(new java.awt.Color(0, 51, 51));
        txtUserId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtUserId.setForeground(new java.awt.Color(255, 255, 255));
        panelLogin.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 260, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        panelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, 40));

        btnLogin.setBackground(new java.awt.Color(0, 51, 51));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 110, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("USER ID");
        panelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("ROLE");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("PASSWORD");
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        buttonGroup1.add(radioAdmin);
        radioAdmin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioAdmin.setText("ADMIN");
        panelLogin.add(radioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        buttonGroup1.add(radioMember);
        radioMember.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        radioMember.setText("MEMBER");
        panelLogin.add(radioMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("(Member only)");
        panelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, -1, -1));

        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });
        panelLogin.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Don't have an account?");
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        mainPanel.add(panelLogin, "card2");

        panelRegister.setBackground(new java.awt.Color(97, 130, 100));
        panelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SIGN UP");
        panelRegister.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 540, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("STATUS");
        panelRegister.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("USER ID");
        panelRegister.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        txtName.setBackground(new java.awt.Color(0, 51, 51));
        txtName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        panelRegister.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 260, 40));

        btnRegister.setBackground(new java.awt.Color(0, 51, 51));
        btnRegister.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        panelRegister.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 110, 40));

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/arrow_back_ios_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        panelRegister.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("NEW PASSWORD");
        panelRegister.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        txtPasswordNew.setBackground(new java.awt.Color(0, 51, 51));
        txtPasswordNew.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtPasswordNew.setForeground(new java.awt.Color(255, 255, 255));
        panelRegister.add(txtPasswordNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 260, 40));

        txtUserIdNew.setBackground(new java.awt.Color(0, 51, 51));
        txtUserIdNew.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtUserIdNew.setForeground(new java.awt.Color(255, 255, 255));
        panelRegister.add(txtUserIdNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("YOUR NAME");
        panelRegister.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        comboStatus.setBackground(new java.awt.Color(0, 51, 51));
        comboStatus.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        comboStatus.setForeground(new java.awt.Color(255, 255, 255));
        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mahasiwa", "Siswa", "Pekerja" }));
        panelRegister.add(comboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 260, 40));

        mainPanel.add(panelRegister, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        btnSignUp.setForeground(Color.white);
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        btnSignUp.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_btnSignUpMouseExited

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        changePanel(mainPanel, panelRegister);
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        changePanel(mainPanel, panelLogin);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            if (txtUserId.getText().matches("(.*)'(.*)") || String.copyValueOf(txtPassword.getPassword()).matches("(.*)'(.*)")) {
                JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
            }else{
                if (txtUserId.getText().equals("") || String.copyValueOf(txtPassword.getPassword()).equals("")) {
                    JOptionPane.showMessageDialog(null, "Username atau Password Tidak Boleh Kosong");
                }else{
                    if (radioAdmin.isSelected()) {
                        boolean operatinSuccess = ControllerAccount.radioAdminSelected(txtUserId.getText(), String.copyValueOf(txtPassword.getPassword()));
                        if (operatinSuccess) {
                            JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN SEBAGAI ADMIN");
                            this.dispose();
                            new AdminGUI().setVisible(true);
                        }else JOptionPane.showMessageDialog(null, "GAGAL LOGIN. HARAP CEK USERNAME,PASSWORD DAN ROLE ANDA");

                    }else if (radioMember.isSelected()) {
                        boolean operatinSuccess = ControllerAccount.radioMemberSelected(txtUserId.getText(), String.copyValueOf(txtPassword.getPassword()));
                        if (operatinSuccess) {
                            JOptionPane.showMessageDialog(null, "ANDA BERHASIL LOGIN SEBAGAI MEMBER");
                            this.dispose();  
                            new MemberGUI(txtUserId.getText()).setVisible(true);
                        }else JOptionPane.showMessageDialog(null, "GAGAL LOGIN. HARAP CEK USERNAME,PASSWORD DAN ROLE ANDA");

                    }else JOptionPane.showMessageDialog(null, "HARAP PILIH ROLE");
                }
            } 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if (txtUserIdNew.getText().matches("(.*)'(.*)") || String.copyValueOf(txtPasswordNew.getPassword()).matches("(.*)'(.*)") || txtName.getText().matches("(.*)'(.*)")) {
            JOptionPane.showMessageDialog(null, "Dilarang Memasukkan Simbol Petik Satu","WARNING",JOptionPane.WARNING_MESSAGE);
        }else {
            if (txtUserIdNew.getText().equals("") || String.copyValueOf(txtPasswordNew.getPassword()).equals("") || txtName.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Username atau Password Tidak Boleh Kosong");
            }else try {
                    ControllerAccount.registerAccount(txtUserIdNew.getText(), String.copyValueOf(txtPasswordNew.getPassword()),txtName.getText(), (String) comboStatus.getSelectedItem());
                    JOptionPane.showMessageDialog(null, "BERHASIL MENDAFTAR");
                    clearField();
                    changePanel(mainPanel, panelLogin);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"USER ID SUDAH ADA, HARAP GUNAKAN YANG LAIN");
            }  
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JRadioButton radioAdmin;
    private javax.swing.JRadioButton radioMember;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordNew;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserIdNew;
    // End of variables declaration//GEN-END:variables
}